db.URL = jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require
db.USER = postgres.mfzfttehsiwymlxszldd
db.PASSWORD = mwtf2KBhndNIRy1E

db.PRODUCT_IMAGE_PATH = https://mfzfttehsiwymlxszldd.supabase.co/storage/v1/object/public/products/

email.user = brandex.project@gmail.com
email.password = xzaz iuex hayz ieqo
